import type { Metadata } from "next";
import "./globals.css";
import { RedHat } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Frontend Mentor | Countdown Launch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={RedHat.variable}>{children}</body>
    </html>
  );
}
